version: 2

sources:
  - name: STAGING
    database: WALLMART
    schema: BRONZE
    tables: 
      - name: STAGING_DEPARTMENT
      - name: STAGING_STORE

  - name: EXISTING
    database: WALLMART
    schema: BRONZE
    tables:
      - name: DATE
      - name: STORE

    